@echo off
setlocal enabledelayedexpansion
REM ============================================================================
REM run-tests.bat - 0323 Cloud Disk one-shot test runner
REM   [1/4] Rebuild libprotocol static lib (ensures tests run against latest source)
REM   [2/4] Build Qt Test project (tests/unit_tests)
REM   [3/4] Run unit tests (BinaryStream / CryptoUtil / ProtocolFactory)
REM   [4/4] clang-tidy static analysis (report -> tests/clang-tidy-report.txt)
REM
REM Usage:
REM   scripts\run-tests.bat               full pipeline
REM   scripts\run-tests.bat --skip-static  unit tests only
REM
REM NOTE: keep this file pure ASCII. cmd's if-block parser treats parentheses
REM       inside a block as nesting - echo text containing ( ) inside a block
REM       silently swallows the rest of the script. Use goto instead.
REM ============================================================================

set "QT_BIN=C:\Qt\5.15.2\mingw81_64\bin"
set "MINGW_BIN=C:\Qt\Tools\mingw810_64\bin"
set "CLANG_BIN=C:\Qt\Tools\QtCreator\bin\clang\bin"
set "PATH=%QT_BIN%;%MINGW_BIN%;%CLANG_BIN%;%PATH%"

set "ROOT=%~dp0.."
cd /d "%ROOT%"

echo.
echo ============================================================
echo  [1/4] Building libprotocol static library
echo ============================================================
cd shared\libprotocol
qmake "CONFIG+=release" "CONFIG-=debug" libprotocol.pro >nul
if errorlevel 1 goto fail_qmake_lib
mingw32-make -j%NUMBER_OF_PROCESSORS% >nul
if errorlevel 1 goto fail_make_lib
if not exist release\libprotocol.a goto fail_missing_lib
echo [OK] libprotocol.a ready
cd ..\..

echo.
echo ============================================================
echo  [2/4] Building unit tests
echo ============================================================
cd tests\unit_tests
qmake "CONFIG+=release" "CONFIG-=debug" unit_tests.pro >nul
if errorlevel 1 goto fail_qmake_tests
mingw32-make -j%NUMBER_OF_PROCESSORS% >nul
if errorlevel 1 goto fail_make_tests
if not exist release\unit_tests.exe goto fail_missing_tests
echo [OK] unit_tests.exe ready

echo.
echo ============================================================
echo  [3/4] Running unit tests
echo ============================================================
release\unit_tests.exe
if errorlevel 1 goto fail_tests
cd ..\..

if "%1"=="--skip-static" goto skip_static

echo.
echo ============================================================
echo  [4/4] clang-tidy static analysis - LLVM 18 from Qt Creator
echo ============================================================
set "GCC=C:\Qt\Tools\mingw810_64"
set "STD_INC=-I%GCC%\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++ -I%GCC%\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\x86_64-w64-mingw32 -I%GCC%\x86_64-w64-mingw32\include -I%GCC%\lib\gcc\x86_64-w64-mingw32\8.1.0\include -I%GCC%\lib\gcc\x86_64-w64-mingw32\8.1.0\include\c++\backward -I%GCC%\include"
set "CHECKS=clang-analyzer-*,bugprone-*,performance-*"
set "REPORT=tests\clang-tidy-report.txt"

echo Scanning... report will be written to %REPORT%
(
    echo ============================================================
    echo  clang-tidy report - generated by scripts\run-tests.bat
    echo  checks: %CHECKS%
    echo  date: %date% %time%
    echo ============================================================
    echo.
    clang-tidy -p="" --checks="%CHECKS%" --header-filter="0323" shared\libprotocol\BinaryStream.cpp -- -std=c++11 -Ishared\libprotocol %STD_INC%
    echo.
    clang-tidy -p="" --checks="%CHECKS%" --header-filter="0323" shared\libprotocol\ProtocolFactory.cpp -- -std=c++11 -Ishared\libprotocol %STD_INC%
    echo.
    clang-tidy -p="" --checks="%CHECKS%" --header-filter="0323" 0323server\security\CryptoUtil.cpp -- -std=c++11 -I0323server\security %STD_INC%
) > "%REPORT%" 2>&1

set "WARN_COUNT=0"
for /f %%L in ('findstr /c:"warning:" "%REPORT%" ^| find /c "warning:"') do set "WARN_COUNT=%%L"
if "!WARN_COUNT!"=="" set "WARN_COUNT=0"

echo.
echo ============================================================
echo  [DONE] all unit tests passed
echo  static analysis: !WARN_COUNT! warnings - see %REPORT%
echo ============================================================
echo.
exit /b 0

:skip_static
echo.
echo [DONE] all unit tests passed - static analysis skipped
exit /b 0

:fail_qmake_lib
echo [FAILED] qmake libprotocol
exit /b 1

:fail_make_lib
echo [FAILED] build libprotocol
exit /b 1

:fail_missing_lib
echo [FAILED] libprotocol.a missing
exit /b 1

:fail_qmake_tests
echo [FAILED] qmake unit_tests
exit /b 1

:fail_make_tests
echo [FAILED] build unit_tests
exit /b 1

:fail_missing_tests
echo [FAILED] unit_tests.exe missing
exit /b 1

:fail_tests
echo.
echo [FAILED] some unit tests failed!
exit /b 1
